# Generated by Django 2.0.1 on 2018-03-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kofuku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grat',
            name='save_grat',
            field=models.BooleanField(default=False),
        ),
    ]
