# Generated by Django 2.0.1 on 2018-03-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kofuku', '0002_grat_save_grat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grat',
            name='save_grat',
            field=models.BooleanField(default=True),
        ),
    ]
